ARG BASE_TAG="1.12.0"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

### Install and update packages
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
    && apt-get install -y apt-utils \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y \
        fonts-powerline \
        xdg-utils # needed for obsidian

WORKDIR $HOME/Downloads
ARG OBSIDIAN_TAG="1.1.9"
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
    && wget "https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_TAG}/obsidian_${OBSIDIAN_TAG}_amd64.deb" \
    && dpkg -i "obsidian_${OBSIDIAN_TAG}_amd64.deb" \
    && rm -f "obsidian_${OBSIDIAN_TAG}_amd64.deb"

COPY ./src/ubuntu/install/obsidian/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh


# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
    && apt-get install -y ttf-* \
    && apt install fonts-noto* \
    && fc-cache -f -v

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
