ARG BASE_TAG="1.15.0"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ARG ICA_VER='23.11.0.82_amd64'

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

### Install sudo
RUN apt-get install -y sudo \
  && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
  && rm -rf /var/lib/apt/list/*

### Install and update packages
RUN apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y \
        apt-transport-https \
        curl \
        git \
        vim \
        tmux \
        python3 \
        python3-pip \
        python3-gpg \
        fonts-powerline \
        xsel \
        xclip \
        jq \
        php8.1 \
        php8.1-curl  \
        php8.1-xml \
        network-manager \
        network-manager-gnome \
        network-manager-openvpn-gnome \
        network-manager-openconnect-gnome

# flatpak
RUN sudo apt install -y flatpak \
  && flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

### Install icaclient
COPY ./bin/icaclient_${ICA_VER}.deb Downloads/
# https://docs.citrix.com/en-us/citrix-workspace-app-for-linux/install.html#debian-packages
RUN export DEBIAN_FRONTEND="noninteractive" \
    && printf "%s\n icaclient app_protection/install_app_protection select no" | debconf-set-selections \
    && apt install -y -f ./Downloads/icaclient_${ICA_VER}.deb \
    && rm -rf ./Downloads/icaclient_${ICA_VER}.deb

### Install Firefox
# https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

#ssl fix for icaclient (doesn't seem to be needed since v22)
#RUN sudo ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts
#RUN sudo c_rehash /opt/Citrix/ICAClient/keystore/cacerts

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
