ARG BASE_TAG="1.12.0"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

### Install sudo
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
  && apt-get install -y sudo \
  && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
  && rm -rf /var/lib/apt/list/*

### Install and update packages
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
    && apt-get install -y apt-utils \
    && apt-get update \
    && apt-get dist-upgrade -y \
    && apt-get install -y \
        apt-transport-https \
        curl \
        git \
        vim \
        tmux \
        python3 \
        python3-pip \
        python3-gpg \
        fonts-powerline \
        xsel \
        xclip \
        jq \
        php8.1 \
        php8.1-curl  \
        php8.1-xml \
        network-manager \
        network-manager-gnome \
        network-manager-openvpn-gnome \
        network-manager-openconnect-gnome \
        xdg-utils # needed for obsidian

WORKDIR $HOME/Downloads
ARG OBSIDIAN_TAG="1.1.9"
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
    && wget "https://github.com/obsidianmd/obsidian-releases/releases/download/v${OBSIDIAN_TAG}/obsidian_${OBSIDIAN_TAG}_amd64.deb" \
    && dpkg -i "obsidian_${OBSIDIAN_TAG}_amd64.deb" \
    && rm -f "obsidian_${OBSIDIAN_TAG}_amd64.deb"

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
